---
title: "P8105 HW6"
author: JingYao Geng
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%", 
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  echo = TRUE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

**1. Data Import**
```{r import1}
homicides = read_csv("./data-homicides-master/homicide-data.csv") %>%
  janitor::clean_names()
```


## Problem 2

**1. Data Import**
```{r import2}
birthweight = read_csv("./data#2/birthweight.csv") %>%
  janitor::clean_names()

# convert numeric to factor
birthweight = 
  birthweight %>%
  mutate(
    babysex = factor(babysex, levels = c(1,2), labels = c("male", "female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), labels = c("white", "black", "asian"," puerto rican", "other", "unknown")),
    malform = factor(malform, labels = c("absent", "present")),
    mrace = factor(mrace,  c(1, 2, 3, 4, 8, 9), labels = c("white", "black", "asian"," puerto rican", "other", "unknown"))
    )

# ways to check the existence of missing values:
sum(is.na(birthweight))
sum(!complete.cases(birthweight))

```

**My model:**

```{r mu_model}

```


**Compare my model to the following two models:**
```{r model_compare}
# One using length at birth and gestational age as predictors (main effects only)
model1 = lm(bwt ~ blength + gaweeks, data = birthweight) %>%
  broom::glance()
#One using head circumference, length, sex, and all interactions (including the three-way interaction) between these
model2 = lm(bwt ~bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex , data = birthweight) %>%
  broom::glance()
```





## Problem 3

**1. Data Import**
```{r import3}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

